#!/bin/sh

# Usage: build has_native

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1

add lib pkg/META		
add lib src/dicomm.mli
add lib src/dicomm.cmti	
add lib src/dicomm.cmi
add lib src/dicomm.cmx
add lib src/dicomm.cma
add lib src/dicomm.a
add lib src/dicomm.cmxa
add lib src/dicomm.cmxs

add bin test/dicomtrip

add doc README.md
add doc CHANGES.md

build
install dicomm
